language: node_js

before_install:
  # - npm install -g npm@11.2 
  - cd frokant
  - nvm install

before_script: cd frokant
script: npm run build

notifications:
  email: false

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $githubtoken
  on:
    branch: master
  local_dir: dist
  fqdn: cook-it.poiters.be
