service:
  name: cook-it

# Add the serverless-webpack plugin
plugins:
  - serverless-webpack

provider:
  stage: dev
  name: aws
  runtime: nodejs8.10
  profile: cook-it-serverless-admin
  region: eu-west-2
  timeout: 1
  memorySize: 128

functions:
  getRecipes:
    handler: recipes.get
    events:
      - http:
          method: get
          path: recipes
